# **Part 1: Python and Pandas**
-Download the dataset and load it into a Pandas DataFrame.

_______
## **Step 1: Understand the Data**
```
Check:
● Number of rows and columns
● Column names
● Data types
● First and last few records
● Basic statistical information
You may use functions such as:
● head()
● tail()
● info()
● describe()
● shape
```

_________
### Upload Dataset using `pandas`
-to read csv file using `read_csv()`

In [74]:
import pandas as pd
delivery_details=pd.read_csv("delivery_data_with_restaurants.csv")
delivery_details

,order_id,order_time,delivery_time,delivery_duration_min,city,state,latitude,longitude,restaurant,is_canceled,cancel_reason,customer_rating
0,e5b99ed3-4bd6-4aed-9583-989823be022d,2025-04-10 13:21:00,2025-04-10 13:58:00,37.0,New York,NY,40.7128,-74.0060,Pasta Place,False,NaN,4.9
1,fd83af05-01fa-4b33-9254-b2708993a58a,2025-01-26 08:45:00,2025-01-26 09:06:00,21.0,Dallas,TX,32.7767,-96.7970,Taco Town,False,NaN,4.8
2,f4ab757f-669e-4b5a-9279-4b88a456fca8,2025-01-20 21:27:00,2025-01-20 22:22:00,55.0,San Jose,CA,37.3382,-121.8863,Burger Haven,False,NaN,4.1
3,8e4247d0-c211-445b-81c0-3d13e9101398,2024-12-12 16:17:00,2024-12-12 16:55:00,38.0,San Diego,CA,32.7157,-117.1611,Seafood Delight,False,NaN,4.7
4,65c2f48f-4a3c-4159-8eaf-22ae6a1fbff2,2025-03-01 14:24:00,2025-03-01 14:47:00,23.0,Philadelphia,PA,39.9526,-75.1652,The Gourmet Kitchen,False,NaN,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,cb598861-e313-4836-873d-93a788b8150c,2025-04-20 18:18:00,2025-04-20 19:07:00,49.0,Los Angeles,CA,34.0522,-118.2437,Taco Town,False,NaN,3.7
9996,475f4e9d-6288-4d22-8c62-0147faece970,2025-02-06 12:04:00,2025-02-06 13:11:00,67.0,San Antonio,TX,29.4241,-98.4936,Pasta Place,False,NaN,2.8
9997,9e9a46d2-5d11-4be8-9fd1-3640d431a976,2025-01-22 19:12:00,2025-01-22 19:48:00,36.0,San Antonio,TX,29.4241,-98.4936,Burger Haven,False,NaN,5.0
9998,aafe9464-69d4-4449-a6bf-5d392ddf14ab,2024-11-04 12:33:00,2024-11-04 13:52:00,79.0,San Jose,CA,37.3382,-121.8863,Bistro Belle,False,NaN,3.3
9999,def496b0-2729-4274-948f-c3956eeab6e4,2025-03-07 18:28:00,2025-03-07 19:52:00,84.0,Philadelphia,PA,39.9526,-75.1652,Taco Town,False,NaN,2.0

____________
### **Number of rows and columns**
- to view the row count then use `shape[0]`
- to view the column count then use `shape[1]`

In [75]:
print("Number of Rows:",delivery_details.shape[0])
print("Number of Columns:",delivery_details.shape[1])

Number of Rows: 10000
Number of Columns: 12

__________
### **Column names**
- to view the column_name then use `.columns` object

In [76]:
delivery_details.columns

Index(['order_id', 'order_time', 'delivery_time', 'delivery_duration_min',
       'city', 'state', 'latitude', 'longitude', 'restaurant', 'is_canceled',
       'cancel_reason', 'customer_rating'],
      dtype='object')

In [77]:
# for cleaner output
for col in delivery_details.columns:
    print(col)

order_id
order_time
delivery_time
delivery_duration_min
city
state
latitude
longitude
restaurant
is_canceled
cancel_reason
customer_rating

___________
###  Data types
- using the `.dtypes` instance

In [78]:
delivery_details.dtypes

order_id                  object
order_time                object
delivery_time             object
delivery_duration_min    float64
city                      object
state                     object
latitude                 float64
longitude                float64
restaurant                object
is_canceled                 bool
cancel_reason             object
customer_rating          float64
dtype: object

____________
### **First and last few records**
- first few `head(10)`
- last few `tail(10)`

In [79]:
print("First 10")
delivery_details.head(10)

First 10

,order_id,order_time,delivery_time,delivery_duration_min,city,state,latitude,longitude,restaurant,is_canceled,cancel_reason,customer_rating
0,e5b99ed3-4bd6-4aed-9583-989823be022d,2025-04-10 13:21:00,2025-04-10 13:58:00,37.0,New York,NY,40.7128,-74.0060,Pasta Place,False,NaN,4.9
1,fd83af05-01fa-4b33-9254-b2708993a58a,2025-01-26 08:45:00,2025-01-26 09:06:00,21.0,Dallas,TX,32.7767,-96.7970,Taco Town,False,NaN,4.8
2,f4ab757f-669e-4b5a-9279-4b88a456fca8,2025-01-20 21:27:00,2025-01-20 22:22:00,55.0,San Jose,CA,37.3382,-121.8863,Burger Haven,False,NaN,4.1
3,8e4247d0-c211-445b-81c0-3d13e9101398,2024-12-12 16:17:00,2024-12-12 16:55:00,38.0,San Diego,CA,32.7157,-117.1611,Seafood Delight,False,NaN,4.7
4,65c2f48f-4a3c-4159-8eaf-22ae6a1fbff2,2025-03-01 14:24:00,2025-03-01 14:47:00,23.0,Philadelphia,PA,39.9526,-75.1652,The Gourmet Kitchen,False,NaN,4.6
5,eeb31c56-fbfa-49ce-b0b3-db1924fdb709,2024-11-01 14:30:00,2024-11-01 15:03:00,33.0,San Diego,CA,32.7157,-117.1611,Bistro Belle,False,NaN,4.6
6,2333efc9-a8a3-4b96-9e64-9a6ebcf96709,2025-03-30 11:07:00,2025-03-30 11:44:00,37.0,Houston,TX,29.7604,-95.3698,The Gourmet Kitchen,False,NaN,4.8
7,0d3a33d8-ad22-4cd1-abd8-822574780661,2024-12-18 10:39:00,2024-12-18 11:41:00,62.0,New York,NY,40.7128,-74.0060,Bistro Belle,False,NaN,3.1
8,8b0dc0d8-e9b1-4eea-8f0c-b9da6609044d,2025-02-11 12:41:00,2025-02-11 13:57:00,76.0,Dallas,TX,32.7767,-96.7970,Vegan Vibes,False,NaN,2.8
9,5fc897a0-571d-4c47-aa39-de76d41cf06e,2025-04-11 12:34:00,2025-04-11 13:08:00,34.0,Chicago,IL,41.8781,-87.6298,Taco Town,False,NaN,4.6

In [12]:
print("Last 10")
delivery_details.tail(10)

Last 10

,order_id,order_time,delivery_time,delivery_duration_min,city,state,latitude,longitude,restaurant,is_canceled,cancel_reason,customer_rating
9990,286e779b-ddbc-41de-b193-f97823188620,2024-12-08 14:43:00,2024-12-08 15:24:00,41.0,San Diego,CA,32.7157,-117.1611,Pasta Place,False,NaN,4.1
9991,2b488b38-2495-4be5-9bf9-4581e18413ea,2024-12-24 10:58:00,2024-12-24 11:34:00,36.0,Dallas,TX,32.7767,-96.7970,The Gourmet Kitchen,False,NaN,4.6
9992,84e562da-0f3b-4885-826d-2ffe947e9f39,2025-01-05 13:51:00,2025-01-05 15:05:00,74.0,Phoenix,AZ,33.4484,-112.0740,The Gourmet Kitchen,False,NaN,2.6
9993,f8ab179d-d759-4a38-bebf-d3b0befade81,2024-11-11 08:49:00,NaN,NaN,San Diego,CA,32.7157,-117.1611,Burger Haven,True,Customer Request,NaN
9994,0fc5da4c-1c15-4ade-8c84-f9f0c43d6d09,2025-04-12 14:23:00,2025-04-12 14:43:00,20.0,San Jose,CA,37.3382,-121.8863,The Gourmet Kitchen,False,NaN,4.8
9995,cb598861-e313-4836-873d-93a788b8150c,2025-04-20 18:18:00,2025-04-20 19:07:00,49.0,Los Angeles,CA,34.0522,-118.2437,Taco Town,False,NaN,3.7
9996,475f4e9d-6288-4d22-8c62-0147faece970,2025-02-06 12:04:00,2025-02-06 13:11:00,67.0,San Antonio,TX,29.4241,-98.4936,Pasta Place,False,NaN,2.8
9997,9e9a46d2-5d11-4be8-9fd1-3640d431a976,2025-01-22 19:12:00,2025-01-22 19:48:00,36.0,San Antonio,TX,29.4241,-98.4936,Burger Haven,False,NaN,5.0
9998,aafe9464-69d4-4449-a6bf-5d392ddf14ab,2024-11-04 12:33:00,2024-11-04 13:52:00,79.0,San Jose,CA,37.3382,-121.8863,Bistro Belle,False,NaN,3.3
9999,def496b0-2729-4274-948f-c3956eeab6e4,2025-03-07 18:28:00,2025-03-07 19:52:00,84.0,Philadelphia,PA,39.9526,-75.1652,Taco Town,False,NaN,2.0

______
### **Basic statistical information**
- using `describe()`

In [5]:
print("Basic Statistical Information")
delivery_details.describe()

Basic Statistical Information

       delivery_duration_min      latitude     longitude  customer_rating
count            8961.000000  10000.000000  10000.000000      8961.000000
mean               49.369490     35.179529    -99.659819         3.916416
std                17.655349      4.260429     16.537018         0.895868
min                20.000000     29.424100   -121.886300         1.000000
25%                36.000000     32.715700   -117.161100         3.500000
50%                47.000000     34.052200    -98.493600         4.100000
75%                59.000000     39.952600    -87.629800         4.600000
max                90.000000     41.878100    -74.006000         5.000000

____
### Using ***info()*** we can view,
It displays the,
   ```
   - total rows, 
   - columns, 
   - column names, 
   - data types, 
   - and memory usage.
   ```

In [9]:
print("""It displays the total rows,
columns, 
column names, 
data types, 
and memory usage.\n""")
delivery_details.info()

It displays the total rows,
columns,
column names,
data types,
and memory usage.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               10000 non-null  object
 1   order_time             10000 non-null  object
 2   delivery_time          8961 non-null   object
 3   delivery_duration_min  8961 non-null   float64
 4   city                   10000 non-null  object
 5   state                  10000 non-null  object
 6   latitude               10000 non-null  float64
 7   longitude              10000 non-null  float64
 8   restaurant             10000 non-null  object
 9   is_canceled            10000 non-null  bool
 10  cancel_reason          1039 non-null   object
 11  customer_rating        8961 non-null   float64
dtypes: bool(1), float64(4), object(7)
memory usage: 869.3+ KB

_____________________
## **Step 2: Data Cleaning**
```
Perform the following:
● Check missing values
● Handle missing values where required
● Identify duplicate rows
● Remove duplicates if necessary
● Correct incorrect data types
● Check invalid or unusual values
```

_______________________________________________________________________________________
### **Check missing values**
- using `.isnull()` and `.sum()`
- `isnull()` using to check and view null values
- `sum()` using to calculate the count of missing values.

In [80]:
print("Missing Values\n")
delivery_details.isnull()

Missing Values

,order_id,order_time,delivery_time,delivery_duration_min,city,state,latitude,longitude,restaurant,is_canceled,cancel_reason,customer_rating
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,False,False,False,False,False,True,False
9996,False,False,False,False,False,False,False,False,False,False,True,False
9997,False,False,False,False,False,False,False,False,False,False,True,False
9998,False,False,False,False,False,False,False,False,False,False,True,False
9999,False,False,False,False,False,False,False,False,False,False,True,False

## Working of `.isnull()`
- if the cell has **`NO DATA`** then it will show **`TRUE`**
- if the cell has **`DATA`** then it will show **`FALSE`**
__________________________________________________________________________________________________________
## Working of `.isnull().sum()`
- `.sum()` using to count the total `null values`
- if `0` ,indicates column has `NO NULL VALUES` in column
- if `COUNT OF NULL VALUES` ,incicates column has `NULL VALUES` in column
____________________________________________________________________________________________________________
- **What it does:** It adds up the results from the step above for each column.
- **Behind the scenes:** In Python, the computer reads True as 1 and False as 0.
-  By summing them up, Python is literally counting how many True (missing) values exist in each column.

In [81]:
print("Missing Values\n")
delivery_details.isnull().sum()

Missing Values

order_id                    0
order_time                  0
delivery_time            1039
delivery_duration_min    1039
city                        0
state                       0
latitude                    0
longitude                   0
restaurant                  0
is_canceled                 0
cancel_reason            8961
customer_rating          1039
dtype: int64

In [82]:
delivery_details.dtypes

order_id                  object
order_time                object
delivery_time             object
delivery_duration_min    float64
city                      object
state                     object
latitude                 float64
longitude                float64
restaurant                object
is_canceled                 bool
cancel_reason             object
customer_rating          float64
dtype: object

___________
###  **Handle missing values where required**
-  check which column has missing value
-  then fill required data where it needed
-  using `fillna()`

In [83]:
delivery_details

,order_id,order_time,delivery_time,delivery_duration_min,city,state,latitude,longitude,restaurant,is_canceled,cancel_reason,customer_rating
0,e5b99ed3-4bd6-4aed-9583-989823be022d,2025-04-10 13:21:00,2025-04-10 13:58:00,37.0,New York,NY,40.7128,-74.0060,Pasta Place,False,NaN,4.9
1,fd83af05-01fa-4b33-9254-b2708993a58a,2025-01-26 08:45:00,2025-01-26 09:06:00,21.0,Dallas,TX,32.7767,-96.7970,Taco Town,False,NaN,4.8
2,f4ab757f-669e-4b5a-9279-4b88a456fca8,2025-01-20 21:27:00,2025-01-20 22:22:00,55.0,San Jose,CA,37.3382,-121.8863,Burger Haven,False,NaN,4.1
3,8e4247d0-c211-445b-81c0-3d13e9101398,2024-12-12 16:17:00,2024-12-12 16:55:00,38.0,San Diego,CA,32.7157,-117.1611,Seafood Delight,False,NaN,4.7
4,65c2f48f-4a3c-4159-8eaf-22ae6a1fbff2,2025-03-01 14:24:00,2025-03-01 14:47:00,23.0,Philadelphia,PA,39.9526,-75.1652,The Gourmet Kitchen,False,NaN,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,cb598861-e313-4836-873d-93a788b8150c,2025-04-20 18:18:00,2025-04-20 19:07:00,49.0,Los Angeles,CA,34.0522,-118.2437,Taco Town,False,NaN,3.7
9996,475f4e9d-6288-4d22-8c62-0147faece970,2025-02-06 12:04:00,2025-02-06 13:11:00,67.0,San Antonio,TX,29.4241,-98.4936,Pasta Place,False,NaN,2.8
9997,9e9a46d2-5d11-4be8-9fd1-3640d431a976,2025-01-22 19:12:00,2025-01-22 19:48:00,36.0,San Antonio,TX,29.4241,-98.4936,Burger Haven,False,NaN,5.0
9998,aafe9464-69d4-4449-a6bf-5d392ddf14ab,2024-11-04 12:33:00,2024-11-04 13:52:00,79.0,San Jose,CA,37.3382,-121.8863,Bistro Belle,False,NaN,3.3
9999,def496b0-2729-4274-948f-c3956eeab6e4,2025-03-07 18:28:00,2025-03-07 19:52:00,84.0,Philadelphia,PA,39.9526,-75.1652,Taco Town,False,NaN,2.0

In [69]:
delivery_details[delivery_details["delivery_time"].isnull()].head()

,order_id,order_time,delivery_time,delivery_duration_min,city,state,latitude,longitude,restaurant,is_canceled,cancel_reason,customer_rating
11,1dc8e974-ce17-48b2-a8c1-ff59e8a17a92,2025-02-20 15:42:00,NaT,NaN,Los Angeles,CA,34.0522,-118.2437,Bistro Belle,Canceled,Other,NaN
20,7b2bdaf1-c344-4227-91b5-bbbc3fbf7e32,2025-03-04 08:25:00,NaT,NaN,Los Angeles,CA,34.0522,-118.2437,Steakhouse King,Canceled,Payment Issue,NaN
22,0eeeb174-0374-4ecf-8eea-ecc45ca7b371,2025-04-18 12:33:00,NaT,NaN,San Antonio,TX,29.4241,-98.4936,Sushi World,Canceled,Customer Request,NaN
44,51b92505-1a3b-4037-90c6-19fd1d5410f6,2025-03-05 17:59:00,NaT,NaN,Chicago,IL,41.8781,-87.6298,Sushi World,Canceled,Scam,NaN
46,ee91b8e6-ceb0-4893-b351-50dfe8ad5663,2025-03-05 11:26:00,NaT,NaN,Philadelphia,PA,39.9526,-75.1652,Burger Haven,Canceled,Other,NaN

In [84]:
delivery_details.isnull().sum()

order_id                    0
order_time                  0
delivery_time            1039
delivery_duration_min    1039
city                        0
state                       0
latitude                    0
longitude                   0
restaurant                  0
is_canceled                 0
cancel_reason            8961
customer_rating          1039
dtype: int64


### Remove duplicates if necessary

In [110]:
delivery_details["cancel_reason"] = delivery_details["cancel_reason"].fillna("Not Cancelled")

In [111]:
delivery_details

,order_id,order_time,delivery_time,delivery_duration_min,city,state,latitude,longitude,restaurant,is_canceled,cancel_reason,customer_rating,Delivery_Status
0,e5b99ed3-4bd6-4aed-9583-989823be022d,2025-04-10 13:21:00,2025-04-10 13:58:00,37.0,New York,NY,40.7128,-74.0060,Pasta Place,False,Not Cancelled,4.9,Normal
1,fd83af05-01fa-4b33-9254-b2708993a58a,2025-01-26 08:45:00,2025-01-26 09:06:00,21.0,Dallas,TX,32.7767,-96.7970,Taco Town,False,Not Cancelled,4.8,Fast
2,f4ab757f-669e-4b5a-9279-4b88a456fca8,2025-01-20 21:27:00,2025-01-20 22:22:00,55.0,San Jose,CA,37.3382,-121.8863,Burger Haven,False,Not Cancelled,4.1,Delayed
3,8e4247d0-c211-445b-81c0-3d13e9101398,2024-12-12 16:17:00,2024-12-12 16:55:00,38.0,San Diego,CA,32.7157,-117.1611,Seafood Delight,False,Not Cancelled,4.7,Normal
4,65c2f48f-4a3c-4159-8eaf-22ae6a1fbff2,2025-03-01 14:24:00,2025-03-01 14:47:00,23.0,Philadelphia,PA,39.9526,-75.1652,The Gourmet Kitchen,False,Not Cancelled,4.6,Fast
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,cb598861-e313-4836-873d-93a788b8150c,2025-04-20 18:18:00,2025-04-20 19:07:00,49.0,Los Angeles,CA,34.0522,-118.2437,Taco Town,False,Not Cancelled,3.7,Delayed
9996,475f4e9d-6288-4d22-8c62-0147faece970,2025-02-06 12:04:00,2025-02-06 13:11:00,67.0,San Antonio,TX,29.4241,-98.4936,Pasta Place,False,Not Cancelled,2.8,Delayed
9997,9e9a46d2-5d11-4be8-9fd1-3640d431a976,2025-01-22 19:12:00,2025-01-22 19:48:00,36.0,San Antonio,TX,29.4241,-98.4936,Burger Haven,False,Not Cancelled,5.0,Normal
9998,aafe9464-69d4-4449-a6bf-5d392ddf14ab,2024-11-04 12:33:00,2024-11-04 13:52:00,79.0,San Jose,CA,37.3382,-121.8863,Bistro Belle,False,Not Cancelled,3.3,Delayed
9999,def496b0-2729-4274-948f-c3956eeab6e4,2025-03-07 18:28:00,2025-03-07 19:52:00,84.0,Philadelphia,PA,39.9526,-75.1652,Taco Town,False,Not Cancelled,2.0,Delayed

In [112]:
delivery_details.isnull().sum()

order_id                    0
order_time                  0
delivery_time            1039
delivery_duration_min    1039
city                        0
state                       0
latitude                    0
longitude                   0
restaurant                  0
is_canceled                 0
cancel_reason               0
customer_rating          1039
Delivery_Status             0
dtype: int64

In [120]:
median_rating = delivery_details["customer_rating"].median()

delivery_details["customer_rating"] = delivery_details["customer_rating"].fillna(median_rating)

In [119]:
delivery_details.isnull().sum()

order_id                    0
order_time                  0
delivery_time            1039
delivery_duration_min    1039
city                        0
state                       0
latitude                    0
longitude                   0
restaurant                  0
is_canceled                 0
cancel_reason               0
customer_rating             0
Delivery_Status             0
dtype: int64

In [121]:
median_duration = delivery_details["delivery_duration_min"].median()

delivery_details["delivery_duration_min"] = delivery_details[
    "delivery_duration_min"
].fillna(median_duration)

In [122]:
delivery_details.isnull().sum()

order_id                    0
order_time                  0
delivery_time            1039
delivery_duration_min       0
city                        0
state                       0
latitude                    0
longitude                   0
restaurant                  0
is_canceled                 0
cancel_reason               0
customer_rating             0
Delivery_Status             0
dtype: int64

In [123]:
delivery_details["delivery_time"] = delivery_details["delivery_time"].fillna(
    delivery_details["order_time"]
)

In [124]:
delivery_details.isnull().sum()

order_id                 0
order_time               0
delivery_time            0
delivery_duration_min    0
city                     0
state                    0
latitude                 0
longitude                0
restaurant               0
is_canceled              0
cancel_reason            0
customer_rating          0
Delivery_Status          0
dtype: int64

In [125]:
delivery_details

,order_id,order_time,delivery_time,delivery_duration_min,city,state,latitude,longitude,restaurant,is_canceled,cancel_reason,customer_rating,Delivery_Status
0,e5b99ed3-4bd6-4aed-9583-989823be022d,2025-04-10 13:21:00,2025-04-10 13:58:00,37.0,New York,NY,40.7128,-74.0060,Pasta Place,False,Not Cancelled,4.9,Normal
1,fd83af05-01fa-4b33-9254-b2708993a58a,2025-01-26 08:45:00,2025-01-26 09:06:00,21.0,Dallas,TX,32.7767,-96.7970,Taco Town,False,Not Cancelled,4.8,Fast
2,f4ab757f-669e-4b5a-9279-4b88a456fca8,2025-01-20 21:27:00,2025-01-20 22:22:00,55.0,San Jose,CA,37.3382,-121.8863,Burger Haven,False,Not Cancelled,4.1,Delayed
3,8e4247d0-c211-445b-81c0-3d13e9101398,2024-12-12 16:17:00,2024-12-12 16:55:00,38.0,San Diego,CA,32.7157,-117.1611,Seafood Delight,False,Not Cancelled,4.7,Normal
4,65c2f48f-4a3c-4159-8eaf-22ae6a1fbff2,2025-03-01 14:24:00,2025-03-01 14:47:00,23.0,Philadelphia,PA,39.9526,-75.1652,The Gourmet Kitchen,False,Not Cancelled,4.6,Fast
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,cb598861-e313-4836-873d-93a788b8150c,2025-04-20 18:18:00,2025-04-20 19:07:00,49.0,Los Angeles,CA,34.0522,-118.2437,Taco Town,False,Not Cancelled,3.7,Delayed
9996,475f4e9d-6288-4d22-8c62-0147faece970,2025-02-06 12:04:00,2025-02-06 13:11:00,67.0,San Antonio,TX,29.4241,-98.4936,Pasta Place,False,Not Cancelled,2.8,Delayed
9997,9e9a46d2-5d11-4be8-9fd1-3640d431a976,2025-01-22 19:12:00,2025-01-22 19:48:00,36.0,San Antonio,TX,29.4241,-98.4936,Burger Haven,False,Not Cancelled,5.0,Normal
9998,aafe9464-69d4-4449-a6bf-5d392ddf14ab,2024-11-04 12:33:00,2024-11-04 13:52:00,79.0,San Jose,CA,37.3382,-121.8863,Bistro Belle,False,Not Cancelled,3.3,Delayed
9999,def496b0-2729-4274-948f-c3956eeab6e4,2025-03-07 18:28:00,2025-03-07 19:52:00,84.0,Philadelphia,PA,39.9526,-75.1652,Taco Town,False,Not Cancelled,2.0,Delayed

### Identify duplicate rows

In [126]:
delivery_details.duplicated().sum()

np.int64(0)

### Correct incorrect data types

In [127]:
delivery_details["delivery_time"] = pd.to_datetime(delivery_details["delivery_time"])
delivery_details["order_time"] = pd.to_datetime(delivery_details["order_time"])
delivery_details.dtypes

order_id                         object
order_time               datetime64[ns]
delivery_time            datetime64[ns]
delivery_duration_min           float64
city                             object
state                            object
latitude                        float64
longitude                       float64
restaurant                       object
is_canceled                        bool
cancel_reason                    object
customer_rating                 float64
Delivery_Status                  object
dtype: object

In [128]:
delivery_details.isnull().sum()

order_id                 0
order_time               0
delivery_time            0
delivery_duration_min    0
city                     0
state                    0
latitude                 0
longitude                0
restaurant               0
is_canceled              0
cancel_reason            0
customer_rating          0
Delivery_Status          0
dtype: int64

# Step 3: Create a New Column
```
Create a column called:
Delivery_Status

Use the following conditions:
● Delivery time less than or equal to 30 minutes: Fast
● Delivery time between 31 and 45 minutes: Normal
● Delivery time greater than 45 minutes: Delayed
```

In [129]:
import numpy as np

In [130]:
delivery_details["Delivery_Status"] = np.where(
    delivery_details["delivery_duration_min"] <= 30,
    "Fast",
    np.where(
        delivery_details["delivery_duration_min"] <= 45,
        "Normal",
        "Delayed"
    )
)

In [131]:
delivery_details.head()

,order_id,order_time,delivery_time,delivery_duration_min,city,state,latitude,longitude,restaurant,is_canceled,cancel_reason,customer_rating,Delivery_Status
0,e5b99ed3-4bd6-4aed-9583-989823be022d,2025-04-10 13:21:00,2025-04-10 13:58:00,37.0,New York,NY,40.7128,-74.0060,Pasta Place,False,Not Cancelled,4.9,Normal
1,fd83af05-01fa-4b33-9254-b2708993a58a,2025-01-26 08:45:00,2025-01-26 09:06:00,21.0,Dallas,TX,32.7767,-96.7970,Taco Town,False,Not Cancelled,4.8,Fast
2,f4ab757f-669e-4b5a-9279-4b88a456fca8,2025-01-20 21:27:00,2025-01-20 22:22:00,55.0,San Jose,CA,37.3382,-121.8863,Burger Haven,False,Not Cancelled,4.1,Delayed
3,8e4247d0-c211-445b-81c0-3d13e9101398,2024-12-12 16:17:00,2024-12-12 16:55:00,38.0,San Diego,CA,32.7157,-117.1611,Seafood Delight,False,Not Cancelled,4.7,Normal
4,65c2f48f-4a3c-4159-8eaf-22ae6a1fbff2,2025-03-01 14:24:00,2025-03-01 14:47:00,23.0,Philadelphia,PA,39.9526,-75.1652,The Gourmet Kitchen,False,Not Cancelled,4.6,Fast

# Step 4: Perform Basic Analysis
```
Using Pandas, calculate:
1. Total number of orders
2. Average delivery time
3. Cancellation percentage
4. Average customer rating
5. Restaurant with the highest average delivery time
6. Location with the highest number of delayed orders

Export the cleaned dataset as:
cleaned_food_delivery.csv
```

### Total number of orders

In [132]:
total_orders = delivery_details["order_id"].count()
print("Total number of orders:", total_orders)

Total number of orders: 10000

### Average delivery time

In [133]:
avg_delivery_time = delivery_details["delivery_duration_min"].mean()
print("Average delivery time:", round(avg_delivery_time, 2))

Average delivery time: 49.12

### Cancellation percentage

In [134]:
cancellation_percentage = delivery_details["is_canceled"].mean() * 100
print("Cancellation Percentage:", round(cancellation_percentage, 2), "%")

Cancellation Percentage: 10.39 %

### Average customer rating

In [135]:
average_rating = delivery_details["customer_rating"].mean()
print("Average Customer Rating:", round(average_rating, 2))

Average Customer Rating: 3.94

###  Restaurant with the highest average delivery time

In [136]:
restaurant_avg_delivery = delivery_details.groupby("restaurant")["delivery_duration_min"].mean()
restaurant_highest_delivery = restaurant_avg_delivery.idxmax()
print("Restaurant:", restaurant_highest_delivery)
print("Average Delivery Time:", restaurant_avg_delivery.max())

Restaurant: Pasta Place
Average Delivery Time: 49.552475247524754

### Location with the highest number of delayed orders

In [137]:
delayed_orders = delivery_details[delivery_details["Delivery_Status"] == "Delayed"]
delayed_by_location = delayed_orders.groupby("city").size()
print("Location with highest delayed orders:", delayed_by_location.idxmax())
print("Number of delayed orders:", delayed_by_location.max())

Location with highest delayed orders: San Antonio
Number of delayed orders: 627

### Exporting the cleaned dataset

In [138]:
delivery_details.to_csv("cleaned_food_delivery.csv", index=False)